import type { Metadata } from "next";
import WorldIcon from "@/images/favicon.png";
import Providers from "@/components/Providers";

import "./globals.scss";

export const metadata: Metadata = {
  title: "World Clock App",
  description: "Generated by create next app",
  icons: {
    icon: WorldIcon.src
  }
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;